@baseUrl = http://localhost:3000
@hostname = localhost
@port = 3000

# Rellena estos valores según las respuestas que vayas obteniendo
@accessToken = ACCESS_TOKEN_AQUI
@refreshToken = REFRESH_TOKEN_AQUI
@validationCode = CODIGO_6_DIGITOS_AQUI


### Registro de usuario //OK
POST {{baseUrl}}/api/user/register
Content-Type: application/json

{
  "email": "test2@bildyapp.com",
  "password": "12345678"
}


### Validación de email //OK

PUT {{baseUrl}}/api/user/validation
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "code": "{{validationCode}}"
}


### Login //OK
POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "email": "test2@bildyapp.com",
  "password": "12345678"
}


### Onboarding - datos personales //OK

PUT {{baseUrl}}/api/user/register
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Pepe",
  "lastName": "García López",
  "nif": "12345678Z"
}


### Onboarding - crear o asociar compañía //OK
PATCH {{baseUrl}}/api/user/company
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Bildy Solutions SL",
  "cif": "B12345678",
  "address": {
    "street": "Gran Via",
    "number": "25",
    "postal": "28013",
    "city": "Madrid",
    "province": "Madrid"
  },
  "isFreelance": false
}


### Onboarding - autónomo //OK

PATCH {{baseUrl}}/api/user/company
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Pepe García López",
  "cif": "12345678Z",
  "address": {
    "street": "Gran Via",
    "number": "25",
    "postal": "28013",
    "city": "Madrid",
    "province": "Madrid"
  },
  "isFreelance": true
}


### Obtener usuario autenticado //OK

GET {{baseUrl}}/api/user
Authorization: Bearer {{accessToken}}


### Subir logo de la compañía //OK

PATCH {{baseUrl}}/api/user/logo
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="logo"; filename="logo.png"
Content-Type: image/png

< ./logo.png
--boundary--


### Refresh token //OK
POST {{baseUrl}}/api/user/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}


### Logout //OK
POST {{baseUrl}}/api/user/logout
Authorization: Bearer {{accessToken}}
Content-Type: application/json


### Cambiar contraseña //OK

PUT {{baseUrl}}/api/user/password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "12345678",
  "newPassword": "123456789"
}


### Login con contraseña nueva //OK

POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
  "email": "test2@bildyapp.com",
  "password": "123456789"
}


### Invitar compañero //OK

POST {{baseUrl}}/api/user/invite
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": "guest1@bildyapp.com",
  "password": "12345678",
  "name": "Invitado",
  "lastName": "Uno",
  "nif": "87654321X"
}


### Eliminar usuario - soft delete //OK
DELETE {{baseUrl}}/api/user?soft=true
Authorization: Bearer {{accessToken}}


### Eliminar usuario - hard delete //OK
DELETE {{baseUrl}}/api/user
Authorization: Bearer {{accessToken}}